import pandas as pd
import json
import requests

BB_api_key = os.environ['BB_api_key']


def connect_api():

    url = "https://bb-finance.p.rapidapi.com/news/list"
    querystring = {"id": "stocks"}

    headers = {
        "X-RapidAPI-Key": BB_api_key,
        "X-RapidAPI-Host": "bb-finance.p.rapidapi.com"
    }

    # Request data from API
    response = requests.request("GET", url, headers=headers, params=querystring)

    # Save data in json format
    data = json.loads(response.text)

    return data


def extract_articles(data):
    mydict = {}

    # Separate articles from videos and save text data to dictionary
    for i in range(len(data['modules'][0]['stories'])):
        if data['modules'][0]['stories'][i]['id'].startswith('2022'):
            mydict[data['modules'][0]['stories'][i]['internalID']] = {
                'title': data['modules'][0]['stories'][i]['title'],
                'summary': data['modules'][0]['stories'][i]['summary'],
                'shortUrl': data['modules'][0]['stories'][i]['shortURL'],
                'autoGeneratedSummary': data['modules'][0]['stories'][i]['autoGeneratedSummary'],
                'secondaryBrands': data['modules'][0]['stories'][i]['secondaryBrands'],
                'byline': data['modules'][0]['stories'][i]['byline'],
                'primaryCategory': data['modules'][0]['stories'][i]['primaryCategory'],
                'primarySite': data['modules'][0]['stories'][i]['primarySite'],
                'card': data['modules'][0]['stories'][i]['card']
                }

    # Save dictionary as df
    article_df = pd.DataFrame(mydict).T.reset_index().rename(columns={'index': 'id'})

    return article_df


def extract_videos(data):
    # Same proces but for videos

    videodict = {}

    for i in range(len(data['modules'][0]['stories'])):
        if not data['modules'][0]['stories'][i]['id'].startswith('2022'):
            videodict[data['modules'][0]['stories'][i]['internalID']] = {
                'title': data['modules'][0]['stories'][i]['title'],
                'shortUrl': data['modules'][0]['stories'][i]['shortURL'],
                'summary': data['modules'][0]['stories'][i]['summary'],
                'primaryCategory': data['modules'][0]['stories'][i]['primaryCategory'],
                'channel': data['modules'][0]['stories'][i]['channel'],
                'card': data['modules'][0]['stories'][i]['card'], }

    video_df = pd.DataFrame(videodict).T.reset_index().rename(columns={'index': 'id'})

    return video_df


def main():
    print('[Extract] Start')
    print('[Extract] Connecting to API')
    data = connect_api()

    print('[Extract] Collecting articles')
    article_df = extract_articles(data)

    print('[Extract] Collecting videos')
    video_df = extract_videos(data)

    print('[Extract] End.')
